### ISSUE TITLE
Accordian is not spliting the windows in vim7.4

### ISSUE THREAD

**Issue by shaildev123** [mattboehm/vim-accordion#39]
Hi,

I have installed plugin in windows vim7.4.
I opened a file and i am firing a command :Accordian 2 but it is not doing anything.

Please help me out.

**Comment by mattboehm** [comment]
Make sure you're spelling it `Accordion` and not `Accordian` as you spelled it above. If that doesn't fix it, let me know and I can debug it further with you.

**Comment by shaildev123** [comment]
Thanks Mattboehm. I just checked it the spelling is correct. In fact i am not any error after firing this command on gvim.

**Comment by mattboehm** [comment]
When I get home I'll try installing on my windows machine to reproduce. In the meantime, try typing `:Accor` and hitting tab and make sure it tab-completes. If not, the plugin probably isn't installed properly.

Another issue is that it's possible I wasn't clear enough in the docs and you're misunderstanding what the command does. Accordion itself does not make new splits, it just resizes existing ones. So, when you edit a file in vim, first make a handful of vertical splits by running `:vsp` 2 or 3 times. Then try running `:Accordion 2` and see if the splits resize so that only two are visible.

**Comment by wtanksleyjr** [comment]
I'm running in Ubuntu (plus Pathogen), tried the tab-completion with 4 splits open and ":Accor<tab> 3". It autocompletes, and pauses just a bit when I press <enter>, but nothing changes. I've installed only a few hand-selected plugins, like fugitive and sensible.vim.

**Comment by mattboehm** [comment]
@wtanksleyjr Sorry that I didn't see your comment sooner. Assuming those 4 splits are all vsplits, then this definitely sounds like a bug. I will do my best to reproduce locally, but will also try to add a debug mode that can tell users what the current settings are and try to help narrow down why it's not working

**Comment by wtanksleyjr** [comment]
Wait, you mean Accordion only works with "vert" splits? I use only ":new"
and ":diffsplit", almost never "vert". So that might be the problem!

Nonetheless, and either way, I'd be happy to help debug. Right now I'm
using "golden-ratio", which seems nice enough.

**Comment by mattboehm** [comment]
Right now, Accordion defaults to vertical splits, but you add `let g:accordion_mode="h"` to make it globally resize hsplits.

It would probably be a good idea to add `:AccordionH` and `:AccordionV` commands that would override the global setting and be easier for users than adjusting their vimrc.

**Comment by wtanksleyjr** [comment]
Thank you -- then my "bug" report definitely is just my misreading of the
description.

I will note that the documentation makes it very hard to tell this is how
Accordion works, though -- even the animated GIFs don't make it obvious.

**Comment by mattboehm** [comment]
@wtanksleyjr Thanks for the feedback; I've clarified this in the readme by giving it its own section: https://github.com/mattboehm/vim-accordion#horizontal-splits .

I'm going to consider this issue closed, but will create a separate one for `AccordionH` and `AccordionV` commands.
